---
- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  connection: local
  
  vars:
    keypair: JenkinSetup
    instance_type: t2.nano
    ami: ami-0653e888ec96eab9b
    region: us-east-2
    security_group: launch-wizard-1
    
  tasks:
    - name: Launch instance
      ec2:
         aws_access_key: AKIAIIMYCIQBMUQVKJIQ
         aws_secret_key: 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
         key_name: "{{ keypair }}"
         group: "{{security_group}}"
         instance_type: "{{ instance_type }}"
         image: "{{ ami }}"
         wait: true
         region: "{{ region }}"
         count: 1  # default
         count_tag:
            Name: Demo
         instance_tags:
            Name: Demo
         vpc_subnet_id: subnet-6e775d06
         assign_public_ip: yes
      register: ec2

